<?php

use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $user= Data::get('repeat_user')?>
<?php ErrMgr::attach($user) ?>


    <div class="container">
        <div class="row">

            <article class="col-xs-12 maincontent">
                <br><br>
                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h1 class="thin text-center">Criar Conta</h1>
                            <hr>
                            <form action="<?= URL::toRoute('home/signup') ?>" method="Post">
                                <div class="top-margin">
                                    <label>Nome<span class="text-danger">*</span></label>
                                    <input required type="text" value="<?= $user->nome ?>" class="form-control" name="nome" placeholder="Insira um nome">
                                    <?php echo(ErrMgr::bind('nome')) ?>
                                </div>
                                <div class="top-margin">
                                    <label>Email<span class="text-danger">*</span></label>
                                    <input required type="text" value="<?= $user->email ?>" class="form-control" name="email" placeholder="Insira um email">
                                    <?php echo(ErrMgr::bind('email')) ?>
                                </div>
                                <div class="top-margin">
                                    <label>Data de Nascimento<span class="text-danger">*</span></label>
                                    <input required type="date" value="<?= $user->datanasc ?>" class="form-control" name="datanasc" placeholder="Insira a data nascimento">
                                    <?php echo(ErrMgr::bind('datanasc')) ?>
                                </div>
                                <div class="top-margin">
                                    <label>Telefone<span class="text-danger">*</span></label>
                                    <input required type="number" value="<?= $user->telefone ?>" class="form-control" name="telefone" placeholder="Insira um telefone">
                                    <?php echo(ErrMgr::bind('telefone')) ?>
                                </div>
                                <div class="top-margin">
                                    <label>Username<span class="text-danger">*</span></label>
                                    <input required type="text" value="<?= $user->username ?>" class="form-control" name="username" placeholder="Insira um username">
                                    <?php echo(ErrMgr::bind('username')) ?>
                                </div>
                                <div class="top-margin">
                                    <label>Password<span class="text-danger">*</span></label>
                                    <input required type="password" value="<?= $user->password ?>" class="form-control" name="password" placeholder="Insira um password">
                                    <?php echo(ErrMgr::bind('password')) ?>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-lg-8 text-right">
                                        <button class=" btn btn-action" type="submit">Registar</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </article>
        </div>
    </div>