<?php

use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header_operador');
?>
<?php $bilhetes = Data::get('bilhetes'); ?>
<?php $voos = Data::get('voos') ?>

<div class="container">

    <h2 class="text-center top-space">Operador de Checkin</h2>
    <?php
    echo ' <h2 class="text-left top-space"> Voo de ' .$voos->airportorigem->nome. ' - '.$voos->airportodestino->nome.'</h2>';
    ?>
    <h2 class="top-space"></h2>
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-striped">
                <thead>
                <th>Utilizador</th>
                <th>Preço</th>
                <th>Data Compra</th>
                </thead>
                <tbody>
                <?php foreach ($bilhetes as $bilhete){ ?>
                    <tr>
                        <td><?=$bilhete->bilheteuser->nome?></td>
                        <td><?=$bilhete->preco?></td>
                        <td><?=$bilhete->data_compra->format('Y-m-d')?></td>
                        <td>
                            <a href="<?= URL::toRoute('operador/store' ,$bilhete->id)?>" class="btn btn-info" role="button">Fazer Checkin</a>

                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>

</div>

