<?php

use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header_operador');

?>
<?php  $voos = Data::get('voos')?>

<div class="container">
    <h2 class="text-center">Voos</h2>

    <div class="row">
        <div class="col-sm-12">
            <table class="table table-striped">
                <thead>
                <th>Aeroporto Origem</th>
                <th>Aeroporto Destino</th>
                </thead>
                <tbody>
                <?php foreach ($voos as $voo) { ?>
                    <tr>
                        <td><?= $voo->airportorigem->nome ?></td>
                        <td><?= $voo->airportodestino->nome ?></td>
                        <td><a href="<?=URL::toRoute('operador/checkin' , $voo->id) ?>" class="btn btn-info" role="button">Fazer checkins </a> </td>
                    </tr>
              <?php  }?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<?php Layout::includeLayout('footer');