<?php

use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;

Layout::includeLayout('header_passageiro');?>

<?php  $bilhetes = Data::get('bilhetes')?>

<div class="container">

    <h2 class="text-center">Historico de Voos</h2>

    <div class="row">
        <div class="col-sm-12">
            <table class="table table-striped">
                <thead>
                <th>Voo Ida</th>
                <th>Voo Volta</th>
                <th>Preço</th>
                <th>Data de compra</th>
                </thead>
                <tbody>
                <?php foreach ($bilhetes as $bilhete) { ?>
                <tr>
                    <td><?= $bilhete->bilheteida->airportorigem->nome. ' - '. $bilhete->bilheteida->airportodestino->nome?></td>
                    <td><?= $bilhete->bilhetevolta->airportorigem->nome. ' - '. $bilhete->bilhetevolta->airportodestino->nome?></td>
                    <td><?= $bilhete->preco?></td>
                    <td><?= $bilhete->data_compra->format('Y-m-d')?></td>
                </tr>
                <?php  } ?>
                </tbody>
            </table>
        </div>
    </div>

</div>