<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header_passageiro') ?>
<?php $escalas = Data::get('escalas'); ?>
<?php $aeroportos = Data::get('aeroportos'); ?>

<!-- container -->
<div class="container">
    <h2 class="text-center top-space"> Voos</h2>
    <div class="row">
        <div class="col-sm-12">

            <table class="table table-striped">

                <div class="top-margin">

                        <form method="post" action="<?=Url::toRoute('passageiro/selectorigem')?>">
                            <label>Aeroporto Origem <span class="text-danger">*</span></label>
                            <select name="origem" class="form-control">
                                <option selected value="0"> Escolha uma opcao </option>
                                <?php
                                foreach ($aeroportos as $aeroporto) {
                                    echo ' <option value='.$aeroporto->id.'>'.$aeroporto->nome.'</option>';
                                }
                                ?>
                            </select>
                            <br>
                            <div class="row">
                                <div class="col-lg-4 text-middle">
                                    <button class="btn btn-action" type="submit">Procurar</button>
                                </div>
                            </div>
                        </form>

                        <form method="post" action="<?=Url::toRoute('passageiro/selectdestino')?>">
                            <label >Aeroporto Destino <span class="text-danger">*</span></label>
                            <select name="destino" class="form-control">
                                <option selected value="0">Escolha uma opcao </option>
                                <?php
                                foreach ($aeroportos as $aeroporto) {
                                    echo ' <option value='.$aeroporto->id.'>'.$aeroporto->nome.'</option>';
                                }
                                ?>
                            </select>
                            <br>
                            <div class="row">
                                <div class="col-lg-4 text-middle">
                                    <button class="btn btn-action" type="submit">Procurar</button>
                                </div>
                            </div>
                        </form>
                        <br>
                            <form method="post" action="<?=Url::toRoute('passageiro/voos')?>">
                                <div class="row">
                                    <div class="col-lg-4 text-middle">
                                        <button class="btn btn-action" type="submit">Limpar</button>
                                    </div>
                                </div>
                            </form>
                        <br>
                </div>
                    <thead>
                    <th>Aeroporto Origem</th>
                    <th>Aeroporto Destino</th>
                    <th>Data Partida</th>
                    <th>Hora Partida</th>
                    <th>Data Chegada</th>
                    <th>Hora Chegada</th>
                    <th>Distancia</th>

                    </thead>

                    <tbody>
                    <?php foreach ($escalas as $escala) { ?>
                        <tr>
                            <td><?=$escala->airportorigem->nome?></td>
                            <td><?=$escala->airportodestino->nome?></td>
                            <td><?=$escala->data_origem->format('Y-m-d')?></td>
                            <td><?=$escala->hora_origem?></td>
                            <td><?=$escala->data_final->format('Y-m-d')?></td>
                            <td><?=$escala->hora_destino?></td>
                            <td><?=$escala->distancia?></td>
                        </tr>
                    <?php } ?>
                    </tbody>

            </table>

        </div>
        <div class="col-sm-6">
            <br>
            <p>
                <a href="<?=Url::toRoute('passageiro/compra')?>" class="btn btn-info" role="button">Comprar Bilhete</a>
            </p>
        </div>
    </div> <!-- /row -->

</div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>
