<?php


use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('backoffice');?>
<?php $aeroporto = Data::get('aeroporto')?>
<?php ErrMgr::attach($aeroporto) ?>


<div class="container">
    <div class="row">

        <header class="page-header">
            <h1 class="page-title">Novo Aeroporto</h1>
        </header>

        <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form method="post" action="<?= URL::toroute('aeroporto/store')?>">
                        <div class="top-margin">
                            <label>Nome <span class="text-danger">*</span></label>
                            <input type="text" value="<?= $aeroporto->nome  ?>" name="nome" class="form-control" placeholder="Insira o nome do aeroporto">
                            <?= ErrMgr::bind('nome') ?>
                        </div>
                        <div class="top-margin">
                            <label>Localização <span class="text-danger">*</span></label>
                            <input type="text" value="<?= $aeroporto->localizacao  ?>" name="localizacao" class="form-control" placeholder="Insira a Localização">
                            <?= ErrMgr::bind('localizacao') ?>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-lg-4 text-center">
                                <button class="btn btn-action" type="submit">Criar Aeroporto</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
<?php Layout::includeLayout('footer');