<?php


use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header_gestor');?>
<?php $aviao = Data::get('aviao')?>
<?php ErrMgr::attach($aviao) ?>


    <div class="container">
        <div class="row">

            <header class="page-header">
                <h1 class="page-title">Novo Aviao</h1>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">

                        <form method="post" action="<?= URL::toroute('avioes/store')?>">
                            <div class="top-margin">
                                <label>Referrencia <span class="text-danger">*</span></label>
                                <input type="text" value="<?= $aviao->referencia  ?>" name="referencia" class="form-control" placeholder="Insira o nome do aeroporto">
                                <?= ErrMgr::bind('referencia') ?>
                            </div>
                            <div class="top-margin">
                                <label>Lotação <span class="text-danger">*</span></label>
                                <input type="text" value="<?= $aviao->lotacao  ?>" name="lotacao" class="form-control" placeholder="Insira a Localização">
                                <?= ErrMgr::bind('lotacao') ?>
                            </div>
                            <div class="top-margin">
                                <label>Tipo de Avião <span class="text-danger">*</span></label>
                                <input type="text" value="<?= $aviao->tipo_aviao  ?>" name="tipo_aviao" class="form-control" placeholder="Insira a Localização">
                                <?= ErrMgr::bind('tipo_aviao') ?>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-lg-4 text-center">
                                    <button class="btn btn-action" type="submit">Criar Avião</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
<?php Layout::includeLayout('footer');
