<?php

use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('backoffice') ?>
<?php $user= Data::get('user')?>
<?php ErrMgr::attach($user) ?>


<div class="container">
    <div class="row">

        <article class="col-xs-12 maincontent">
            <br><br>
            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h1 class="thin text-center">Novo Utilizador</h1>
                        <hr>
                        <form action="<?= URL::toRoute('user/update', $user->id) ?>" method="post">
                            <div class="top-margin">
                                <label>Nome<span class="text-danger">*</span></label>
                                <input required type="text" value="<?= $user->nome ?>" class="form-control" name="nome" placeholder="Insira um nome">
                                <?php echo(ErrMgr::bind('nome')) ?>
                            </div>
                            <div class="top-margin">
                                <label>Email<span class="text-danger">*</span></label>
                                <input required type="text" value="<?= $user->email ?>" class="form-control" name="email" placeholder="Insira um email">
                                <?php echo(ErrMgr::bind('email')) ?>
                            </div>
                            <div class="top-margin">
                                <label>NIF<span class="text-danger">*</span></label>
                                <input required type="number" value="<?= $user->nif ?>" class="form-control" name="nif" placeholder="Insira o nif">
                                <?php echo(ErrMgr::bind('nif')) ?>
                            </div>
                            <div class="top-margin">
                                <label>Telefone<span class="text-danger">*</span></label>
                                <input required type="number" value="<?= $user->telefone ?>" class="form-control" name="telefone" placeholder="Insira um telefone">
                                <?php echo(ErrMgr::bind('telefone')) ?>
                            </div>
                            <div class="top-margin">
                                <label>Username<span class="text-danger">*</span></label>
                                <input required type="text" value="<?= $user->username ?>" class="form-control" name="username" placeholder="Insira um username">
                                <?php echo(ErrMgr::bind('username')) ?>
                            </div>
                            <div class="top-margin">
                                <label>Password<span class="text-danger">*</span></label>
                                <input required type="password" value="<?= $user->password ?>" class="form-control" name="password" placeholder="Insira um password">
                                <?php echo(ErrMgr::bind('password')) ?>
                            </div>
                            <div class="top-margin">
                                <label>Role <span class="text-danger">*</span></label>
                                <select name="roles" class="form-control">
                                    <option value="admin">Admin</option>
                                    <option value="operadorcheckin">Operador Checkin</option>
                                    <option value="gestorvoo">Gestor voo</option>
                                    <option value="passageiro">Passageiro</option>
                                </select>
                                <?=ErrMgr::bind('roles') ?>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-lg-8 text-right">
                                    <button class=" btn btn-action" type="submit">Novo Utilizador</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </article>
    </div>
</div>