<?php

use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header_gestor') ?>
<?php $voo= Data::get('voo')?>
<?php $aeroportos = Data::get('aeroporto' )?>
<?php ErrMgr::attach($voo) ?>


<div class="container">
    <div class="row">

        <article class="col-xs-12 maincontent">
            <br><br>
            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h1 class="thin text-center">Novo Voo</h1>
                        <hr>
                        <form action="<?= URL::toRoute('voos/store') ?>" method="Post">
                            <div class="top-margin">
                                <label>Aeroporto<span class="text-danger">*</span></label>
                                <select name="aeroporto_origem" class="form-group">
                                    <?php foreach ($aeroportos as $aeroporto) {
                                        echo ' <option value='.$aeroporto->id.'>'.$aeroporto->nome.'</option>';
                                    }
                                    ?>
                                </select>
                                <?= ErrMgr::bind('aeroporto_origem')?>
                            </div>
                            <div class="top-margin">
                                <label>Aeroporto<span class="text-danger">*</span></label>
                                <select name="aeroporto_destino" class="form-group">
                                    <?php foreach ($aeroportos as $aeroporto) {
                                        echo ' <option value='.$aeroporto->id.'>'.$aeroporto->nome.'</option>';
                                    }
                                    ?>
                                </select>
                                <?= ErrMgr::bind('aeroporto_destino')?>
                            </div>
                            <div class="top-margin">
                                <label>Preço do Voo<span class="text-danger">*</span></label>
                                <input required type="number" value="<?= $voo->custo_voo ?>" class="form-control" name="custo_voo" placeholder="Insira o preco do voo">
                                <?php echo(ErrMgr::bind('custo_voo')) ?>
                            </div>


                            <hr>
                            <div class="row">
                                <div class="col-lg-8 text-right">
                                    <button class=" btn btn-action" type="submit">Novo Voo</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </article>
    </div>
</div>